char *u;
int changedirectory(char **arg,char use[]);
void echofunc(char *arg);
void pwdfunc();
char *readline();
char **tokenize1(char *p,char t[]);
int execute(char **tokens);
void sigh(int signum);
void pinfo(char **t1);
void listjobs();
void killall();
void kjobs(char **tokens);
void sigstop(int sig_num);
int pipes(char **tokens);
int a[10000];
char b[10000][100];
int c[10000];
int global;
int initial;
int flag;
char control[2000];
int currpid;
char currname[1000];
